### PR TITLE
Fixes #97: Clears remaining FileInput component state on rerendering

### LINKED ISSUE #97: During recovery, a deleted secret share cannot be reused immediately after deletion
# Bug

## Steps to Reproduce

1. Open Sunder
2. Click **Recover It**
3. Click **Select File**, choose a saved secret share.
4. In the list of secret shares, hover over "Share #1 successfully processed" and click the **X** to delete it.
5. Click **Select File**, choose *the same* saved secret share again.

### Expected Behavior

The secret share is loaded, and a list entry labeled "Share #1 successfully processed" is displayed.

### Actual Behavior

The secret share is not loaded, and no new list entry is created.

### PR DESCRIPTION
**Pull request by mdrose**
## Status

Ready for review

## Description of Changes

Fixes #97 

Clears out the value attribute on the file input element when it gets rerendered. Leftover values from a previous file can prevent the change event from being fired when it's expected to.

### CODE REVIEW

**Comment by mdrose** [comment]
> Can you provide steps to reproduce this behavior or write a test for it?

Yeah, so all you have to do is try to load the same file twice in a row. When the it first renders the screen, the input element has a default blank value. If you load a file, it sets the value on the input element to the selected file's filepath. If you try to select the same file again, it sets the input element to the same value (same path), thus it doesn't trigger the change event, since nothing changed.

Thinking about it some more, I think it might be better to just not use an input tag at all. It's not really designed to be used this way and the `showOpenDialog` function probably better suits this purpose. Using `showOpenDialog` cuts out DOM state issues and just directly opens the file dialog without worrying indirectly triggering an event.

I've pushed another commit that takes that approach instead.

**Comment by mdrose** [comment]
> Can you provide steps to reproduce this behavior or write a test for it?

Yeah, so all you have to do is try to load the same file twice in a row. The first time the screen is rendered, the input element has a default blank value. If you load a file, it sets the value on the input element to the selected file's filepath. If you try to select the same file again, it sets the input element to the same value (same path), thus it doesn't trigger the change event, since nothing changed.

Thinking about it some more, I think it might be better to just not use an input tag at all. It's not really designed to be used this way and the `showOpenDialog` function probably better suits this purpose. Using `showOpenDialog` cuts out DOM state issues and just directly opens the file dialog without worrying indirectly triggering an event.

I've pushed another commit that takes that approach instead. Let me know what you think.

**Comment by liliakai** [comment]
I guess I'm not clear on why you need to fire the onChange if the file selection is unchanged. Can you explain what detrimental effects this has on the user experience? I just want to be specific about what use case we're trying to address here.

In any case, I still think a file input is appropriate here and the smaller diff is much easier to review. ;)

**Comment by mdrose** [comment]
>I guess I'm not clear on why you need to fire the onChange if the file selection is unchanged.
Because a state change has already been made in the Redux store from the original change, but you have this leftover state in the input tag that causes #97, since it prevents the expected action dispatch. The input tag isn't being used as part of a form, but only to trigger a subroutine, essentially, so the data in the tag is superfluous, gets out of sync with the store, and causes a bug.

>Can you explain what detrimental effects this has on the user experience? 
It's explained in #97.

**Comment by mdrose** [comment]
>I guess I'm not clear on why you need to fire the onChange if the file selection is unchanged.

Because a state change has already been made in the Redux store from the original change. When you load the same file a second time, another dispatch is expected to be fired to update the store, but you have this leftover state in the input tag, which prevents the expected action dispatch since it's tied to the onChange event and causes #97. The input tag isn't being used as part of a form, but only to trigger a subroutine, essentially, so the data in the tag is superfluous, gets out of sync with the store, and causes a bug.

>Can you explain what detrimental effects this has on the user experience? 

It's explained in #97.

File: src/components/FileInput.js [hunk 1]
```diff
@@ -20,21 +22,25 @@ export default class FileInput extends Component {
     this.fileInputId = `file-input-${fileCounter++}`;
   }
 
-  onFileChange(event) {
-    const fileList = Array.from(event.target.files);
+  onFileSelection() {
+    let options = {properties: ['openfile']}
```
Comment (liliakai) [inline src/components/FileInput.js]:
```suggestion
    let options = {properties: ['openFile']}
```
This should be `openFile`, capital F, or else no files will be selectable (on osx at least).
